name: AI API Processor

on:
  push:
    branches:
      - main

jobs:
  process-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests # or any other library needed

      - name: Process Files Through AI API
        run: python process_files.py
        env:
          AI_API_KEY: ${{ secrets.AI_API_KEY }}

      - name: Checkout Side Branch
        uses: actions/checkout@v3
        with:
          ref: 'side-branch'
          fetch-depth: 0

      - name: Copy Files to Side Branch
        run: |
          cp -r path/to/generated_files/* path/to/destination/
          git config --global user.name 'Your Name'
          git config --global user.email 'your-email@example.com'
          git add .
          git commit -m "Add generated files"
          git push origin side-branch

