name: Code Check Automation

on:
  push:
    branches:
      - master

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: 'master'
    
    - name: Checkout secondary branch in a different directory
      uses: actions/checkout@v2
      with:
        ref: 'secondary'
        path: 'secondary'
    - name: Get Changed Files
      id: changed-files
      uses: jitterbit/get-changed-files@v1
      with:
        format: 'space-delimited'
        token: ${{ github.token }}