name: Python Code Check and Commit secondary branch

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'main/action-script/**/*.py'
      - '!main/action-script/output/**'

jobs:
  code-check-and-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: 'master'
        token: ${{ secrets.MY_PERSONAL_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install requests pyyaml python-dotenv

    - name: Run Code Check Script and Generate Timestamped Output
      run: |
        TIMESTAMP=$(date +'%Y%m%d%H%M%S')
        python main/action-script/main.py > "main/action-script/output/$TIMESTAMP.txt"
      env:
        EDENAI_PRODUCTION_KEY: ${{ secrets.EDENAI_PRODUCTION_KEY }}

    - name: Checkout the generated-code branch
      uses: actions/checkout@v2
      with:
        ref: 'generated-code'
        token: ${{ secrets.MY_PERSONAL_TOKEN }}
        path: 'generated-code'

    - name: Copy the generated file to the branch and commit
      run: |
        cp main/action-script/output/*.txt generated-code/
        cd generated-code
        git config --global user.name 'GPT 3.5'
        git config --global user.email 'your.email@example.com'
        git add .
        git commit -m "Update generated code - $(date +'%Y-%m-%d %H:%M:%S')"
        git push origin HEAD:generated-code
