#testing creating a new file on secondary branch
name: Create File on Push

on:
  push:
    branches:
      - master

jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: 'master'
          token: ${{ secrets.MY_PERSONAL_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Create new file on secondary branch
        run: |
          # Create or checkout the secondary branch
          git checkout -b secondary || git checkout secondary
          # Create a new file with current date and time
          echo "File created on $(date)" > new-file.txt
          # Add, commit, and push the changes
          git add new-file.txt
          git commit -m "Add new file"
          git push origin secondary
        token: ${{ secrets.MY_PERSONAL_TOKEN }}

