name: Code Check Automation

on:
  push:
    branches:
      - master

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: 'master'
    
    - name: Checkout secondary branch in a different directory
      uses: actions/checkout@v2
      with:
        ref: 'secondary-branch'
        path: 'secondary'
    
name: Code Check Automation

on:
  push:
    branches:
      - main

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: 'main'
        token: ${{ secrets.MY_PERSONAL_TOKEN }}
        
    - name: Checkout secondary branch in a different directory
      uses: actions/checkout@v2
      with:
        ref: 'secondary-branch'
        path: 'secondary'
    
